#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const { DOMParser } = require("@xmldom/xmldom");

const [, , oldFile, newFile, outputFile = "merged.xlf"] = process.argv;

if (!oldFile || !newFile) {
  console.error(`
Usage:

  node merge-xlf.js <old.xlf> <new.xlf> [output.xlf]

Example:

  node merge-xlf.js messages.pl.xlf messages.new.xlf messages.pl.xlf
`);

  process.exit(1);
}

function readFile(file) {
  if (!fs.existsSync(file)) {
    console.error(`File not found: ${file}`);
    process.exit(1);
  }

  return fs.readFileSync(file, "utf8");
}

/**
 * Get all text content from an XML element.
 */
function getTextContent(element) {
  let result = "";

  function walk(node) {
    // Text node or CDATA
    if (node.nodeType === 3 || node.nodeType === 4) {
      result += node.nodeValue || "";
      return;
    }

    for (
      let child = node.firstChild;
      child;
      child = child.nextSibling
    ) {
      walk(child);
    }
  }

  walk(element);

  return result;
}

/**
 * Normalize source text only for comparison.
 *
 * This means:
 *
 *   "Select month"
 *
 * and
 *
 *   " Select   month "
 *
 * will match.
 */
function normalizeSource(value) {
  return value
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Decode the XML entities that can appear in source text.
 */
function decodeXml(value) {
  return value
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&");
}

/**
 * Escape translation before inserting it into XML.
 */
function escapeXml(value) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * ------------------------------------------------------------
 * Read OLD XLIFF
 * ------------------------------------------------------------
 *
 * Build:
 *
 *   source -> target
 *
 * Example:
 *
 *   "Select month" -> "Wybierz miesiąc"
 */
function loadTranslations(oldXml) {
  const parser = new DOMParser();

  const doc = parser.parseFromString(
    oldXml,
    "application/xml"
  );

  const units = Array.from(
    doc.getElementsByTagName("trans-unit")
  );

  const translations = new Map();

  for (const unit of units) {
    const sourceElement =
      unit.getElementsByTagName("source")[0];

    const targetElement =
      unit.getElementsByTagName("target")[0];

    if (!sourceElement || !targetElement) {
      continue;
    }

    const source = getTextContent(sourceElement);
    const target = getTextContent(targetElement);

    if (!source || !target.trim()) {
      continue;
    }

    const key = normalizeSource(source);

    if (translations.has(key)) {
      console.warn(
        `Duplicate source in old file: "${key}"`
      );

      continue;
    }

    translations.set(key, target);
  }

  return translations;
}

/**
 * ------------------------------------------------------------
 * Merge translations into NEW XLIFF
 * ------------------------------------------------------------
 *
 * IMPORTANT:
 *
 * The new XML is NEVER parsed and serialized.
 *
 * We modify only the text around <source>.
 *
 * This preserves the formatting generated by Angular.
 */
function mergeTranslations(newXml, translations) {
  let matched = 0;
  let unmatched = 0;
  let inserted = 0;

  const unmatchedSources = [];

  const result = newXml.replace(
    /(<trans-unit\b[^>]*>)([\s\S]*?)(<\/trans-unit>)/g,
    (fullUnit, openingTag, content, closingTag) => {
      /**
       * Find source.
       */
      const sourceMatch = content.match(
        /<source\b[^>]*>([\s\S]*?)<\/source>/
      );

      if (!sourceMatch) {
        return fullUnit;
      }

      const sourceContent = sourceMatch[1];

      const source = decodeXml(sourceContent);

      const key = normalizeSource(source);

      /**
       * Find existing translation.
       */
      const translation = translations.get(key);

      if (translation === undefined) {
        unmatched++;

        if (unmatchedSources.length < 20) {
          unmatchedSources.push(source);
        }

        return fullUnit;
      }

      matched++;

      /**
       * Determine the indentation used by <source>.
       *
       * For:
       *
       *     <source>Select month</source>
       *     <context-group>
       *
       * we want:
       *
       *     <source>Select month</source>
       *     <target>Wybierz miesiąc</target>
       *     <context-group>
       */
      const sourceEnd = sourceMatch.index + sourceMatch[0].length;

      const afterSource = content.slice(sourceEnd);

      /**
       * Find whitespace immediately after </source>.
       *
       * Example:
       *
       * "\n        <context-group"
       *
       * We extract:
       *
       * "\n        "
       */
      const whitespaceMatch =
        afterSource.match(/^(\r?\n[ \t]*)/);

      let targetPrefix = "\n        ";

      if (whitespaceMatch) {
        targetPrefix = whitespaceMatch[1];
      }

      /**
       * Extract indentation from that whitespace.
       *
       * "\n        " -> "        "
       */
      const indentation =
        targetPrefix.match(/\r?\n([ \t]*)$/)?.[1] ||
        "        ";

      /**
       * Preserve the whitespace style of the source.
       *
       * If Angular generated:
       *
       *     <source>...</source>
       *     <context-group>
       *
       * target becomes:
       *
       *     <source>...</source>
       *     <target>...</target>
       *     <context-group>
       */
      const target =
        `<target>${escapeXml(translation)}</target>`;

      /**
       * Insert target immediately after </source>.
       *
       * We deliberately do NOT modify the whitespace that was
       * already present after </source>.
       */
      const replacement =
        sourceMatch[0] +
        `\n${indentation}` +
        target;

      const newContent =
        content.slice(0, sourceMatch.index) +
        replacement +
        content.slice(sourceEnd);

      inserted++;

      return (
        openingTag +
        newContent +
        closingTag
      );
    }
  );

  return {
    xml: result,
    matched,
    unmatched,
    inserted,
    unmatchedSources,
  };
}


/**
 * ============================================================
 * MAIN
 * ============================================================
 */

const oldXml = readFile(oldFile);
const newXml = readFile(newFile);

console.log(`Old translation file: ${oldFile}`);
console.log(`New Angular file:     ${newFile}`);
console.log("");

/**
 * Load existing translations.
 */
const translations = loadTranslations(oldXml);

console.log(
  `Existing translations found: ${translations.size}`
);

console.log("");

/**
 * Insert translations into new file.
 */
const result = mergeTranslations(
  newXml,
  translations
);

/**
 * Write output.
 */
fs.writeFileSync(
  outputFile,
  result.xml,
  "utf8"
);

/**
 * Report.
 */
console.log("========================================");
console.log("XLIFF merge complete");
console.log("========================================");

console.log(
  `Existing translations: ${translations.size}`
);

console.log(
  `Translations matched:  ${result.matched}`
);

console.log(
  `Targets inserted:      ${result.inserted}`
);

console.log(
  `New/untranslated:      ${result.unmatched}`
);

console.log("");

if (result.unmatchedSources.length > 0) {
  console.log("First unmatched sources:");

  for (const source of result.unmatchedSources) {
    console.log(`  - ${source}`);
  }

  if (
    result.unmatched >
    result.unmatchedSources.length
  ) {
    console.log(
      `  ... and ${
        result.unmatched -
        result.unmatchedSources.length
      } more`
    );
  }

  console.log("");
}

console.log(
  `Output: ${path.resolve(outputFile)}`
);