<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Data\Migrations" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.23.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.2" />
      <PackageReference Include="HawkNet" Version="1.4.4" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.2" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\webFileSharingSystem.Core\webFileSharingSystem.Core.csproj" />
    </ItemGroup>

</Project>
